name: DART_PACKAGE_NAME # TODO change package name
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

# TODO remove unnecessary dependencies
dependencies:
  flutter:
    sdk: flutter

  # utopia libs
  utopia_arch: ^0.5.0+8
  utopia_firebase_crashlytics: ^0.2.0
  utopia_localization_utils: ^0.0.1

  # architecture
  injector: ^4.0.0
  fast_immutable_collections: ^11.0.4

  # firebase
  firebase_core: ^3.15.2

  # platform APIs

  # misc widgets
  flutter_svg: ^2.0.0+1

  # misc utils
  intl: ^0.20.2

  # code generator runtimes
  freezed_annotation: ^3.1.0
  json_annotation: ^4.3.0
  utopia_localization_annotation: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generators
  freezed: ^3.1.0
  json_serializable: ^6.0.1
  build_runner: ^2.4.11
  utopia_localization_generator: ^0.0.2+2

  # lint
  utopia_lints: ^0.0.1+1

flutter:
  uses-material-design: true
