name: DART_PACKAGE_NAME # TODO change package name
description: DESCRIPTION
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.3"

# TODO remove unnecessary dependencies
dependencies:
  flutter:
    sdk: flutter

  # utopia libs
  utopia_arch: ^0.4.0
  utopia_firebase_crashlytics: ^0.1.2+2
  utopia_hooks: ^0.3.1
  utopia_widgets: ^0.0.9+2
  utopia_utils: ^0.2.11

  # architecture
  provider: ^6.0.1
  injector: ^2.0.0
  fast_immutable_collections: ^7.2.1

  # firebase
  firebase_core: ^1.10.0

  # platform APIs

  # misc widgets

  # misc utils

  # code generator runtimes
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generators
  freezed: ^1.0.0
  json_serializable: ^6.0.1
  build_runner: ^2.1.5

  # lint
  utopia_lints: ^0.0.1+1
