name: DART_PACKAGE_NAME # TODO change package name
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

# TODO remove unnecessary dependencies
dependencies:
  flutter:
    sdk: flutter

  # utopia libs
  utopia_arch: ^0.5.0+8
  utopia_firebase_crashlytics: ^0.2.0

  # architecture
  injector: ^2.0.0
  fast_immutable_collections: ^7.2.1

  # firebase
  firebase_core: ^2.4.1

  # platform APIs

  # misc widgets
  flutter_svg: ^2.0.0+1

  # misc utils
  intl: ^0.18.0

  # code generator runtimes
  freezed_annotation: ^2.2.0
  json_annotation: ^4.3.0
  flutter_sheet_localization: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generators
  freezed: ^2.3.2
  json_serializable: ^6.0.1
  build_runner: ^2.1.5
  flutter_sheet_localization_generator:
    git:
      url: https://github.com/Utopia-USS/flutter_sheet_localization.git
      path: flutter_sheet_localization_generator
      ref: deps_update

  # lint
  utopia_lints: ^0.0.1+1

dependency_overrides:
  intl: ^0.18.0
